export const teachingModels = [
  {
    name: "Studio teaching",
    images: ["studio-teaching.png", "studio-teaching-dark.png"],
    textPlace: "bottom",
    comingSoon: false,
  },
  {
    name: "Challenge",
    images: ["challenge.png", "challenge-dark.png"],
    textPlace: "bottom",
    comingSoon: false,
  },
  {
    name: "Which city to go",
    images: ["which-city-to-go.png", "which-city-to-go-dark.png"],
    textPlace: "bottom",
    comingSoon: false,
  },
  {
    name: "Word to word",
    images: ["word-to-word.png", "word-to-word-light.png"],
    textPlace: "center",
    comingSoon: false,
  },
  {
    name: "Expro",
    images: ["expro.png", "expro-light.png"],
    textPlace: "center",
    comingSoon: false,
  },
  {
    name: "Stop motion",
    images: ["stop-motion.png", "stop-motion-light.png"],
    textPlace: "center",
    comingSoon: false,
  },
  {
    name: "Kids",
    images: ["kids.png", "kids-light.png"],
    textPlace: "center",
    comingSoon: false,
  },
  {
    name: "EX Movie",
    images: ["ex-movie.png", "ex-movie-light.png"],
    textPlace: "center",
    comingSoon: false,
  },
  {
    name: "Eye to Eye",
    images: ["eye-to-eye.png"],
    textPlace: "center",
    comingSoon: true,
  },
  {
    name: "a world a world",
    images: [],
    textPlace: "center",
    comingSoon: false,
  },
  {
    name: "Podcast",
    images: [],
    textPlace: "center",
    comingSoon: false,
  },
  {
    name: "زبان به سبک مدرسه",
    images: [],
    textPlace: "center",
    comingSoon: false,
  },
  {
    name: "زبانیتو",
    images: [],
    textPlace: "center",
    comingSoon: false,
  },
];
